### ISSUE TITLE
modify permID to id and use source prefixes for feature source

### ISSUE THREAD

**Issue by jordansread** [USGS-R/necsc-lake-modeling#21]
nhd_permID for NHD medium res. If we have some high-res lakes in there, we may want to use nhdhr_permID for those or something to avoid the confusion.

**Comment by lawinslow** [comment]
Agreed.

**Comment by jordansread** [comment]
This runs into a lot of different parts of the processing chain, so it isn't super trivial. But I think we need to address it now as a priority before it gets harder

**Comment by jordansread** [comment]
- [ ] rename all the files in the driver source (the .RData files)
- [ ] modify the driver data index file to include the naming
- [ ] all output of the spatial joins should be based on id -> nhd_permID
- [ ] more? add them here  
  and of course change these in the code too...

**Comment by jordansread** [comment]
for files on the server: `rename NLDAS_ NLDAS_nhd_ *.RData`

**Comment by lawinslow** [comment]
I think this is done, right?

**Comment by jordansread** [comment]
is done, right 👍
