### ISSUE TITLE
reporting models to ScienceBase

### ISSUE THREAD

**Issue by jordansread** [USGS-R/necsc-lake-modeling#70]
- [x] **report**: model and package versions
- [x] **report**: map of bias (or rmse?)
- [x] **report**: scenario description
- [x] **report**: number of lakes
- [x] **report**: epi, hypo, 50%, 95% bias and RMSE
- [x] **report**: boxplot for bias vs depths
- [x] **data**: table of obs vs modeled
- [x] **data**: JSON for all nmls used

@lawinslow edits to this?

**Comment by lawinslow** [comment]
Parameter sweeps:
- [x] **cd**: multiplier=c(1.0, 1.02, 1.04, 1.06, 1.08, 1.1)
- [x] **secchi**: multiplier=c(1.0, 1.1, 1.2, 1.3, 1.4, 1.5)  (also switch to median)

**Comment by jordansread** [comment]
👍

**Comment by jordansread** [comment]
Actually, shouldn't `kw` start at 1 and get smaller? it is m-1, right? so it needs to get smaller if there is a deep water cold bias

**Comment by jordansread** [comment]
Oh, I see, you are talking about the secchi multiplier?

**Comment by lawinslow** [comment]
Oh yeah, secchi. Changing to make that clear

**Comment by lawinslow** [comment]
Closing this. In latest PR. Also sweeps no longer relevant (more or less).
